In [2]:
import pickle # used to save and restore python objects
import gzip
import numpy as np

# Load the dataset
f = gzip.open('./MNIST_data/mnist.pkl.gz', 'rb')
train_set, valid_set, test_set = pickle.load(f, encoding = 'latin1')
f.close()

# gather intelligence on the data
print(type(train_set))
print(type(test_set))

FileNotFoundError: [Errno 2] No such file or directory: './MNIST_data/mnist.pkl.gz'

In [2]:
# take a closer look
print("Inputs:")
print(train_set[0])
print("Inputs shape is " + str(train_set[0].shape))
print("Input type is " + str(type(train_set[0])))
print("Labels:")
print(train_set[1])
print("Labels shape is" + str(train_set[1].shape))
print("Labels type is " + str(type(train_set[1])))


Inputs:
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
Inputs shape is (50000, 784)
Input type is <class 'numpy.ndarray'>
Labels:
[5 0 4 ..., 8 4 8]
Labels shape is(50000,)
Labels type is <class 'numpy.ndarray'>


In [3]:
import numpy as np
def to_categorical(y, nb_classes):
    """ to_categorical.

    Convert class vector (integers from 0 to nb_classes)
    to binary class matrix, for use with categorical_crossentropy.

    Arguments:
        y: `array`. Class vector to convert.
        nb_classes: `int`. Total number of classes.

    """
    y = np.asarray(y, dtype='int32')
    if not nb_classes:
        nb_classes = np.max(y)+1
    Y = np.zeros((len(y), nb_classes))
    Y[np.arange(len(y)),y] = 1.
    return Y

In [4]:
train_x = train_set[0]
train_y = to_categorical(train_set[1], 10)
test_x = test_set[0]
test_y = to_categorical(test_set[1],10)

# let's see result of categorizing the outputs
print(test_y[:5])

[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]


In [81]:
def generate_batch(batch_size):
    indexes = np.random.randint(49999, size = (batch_size,))
    return train_x[indexes], train_y[indexes]

In [82]:
import tensorflow as tf

In [95]:
# this just helps with using tensorflow inside jupyter
# (basically, resets/clears all the tensorflow variables)
tf.reset_default_graph()

In [96]:
# for members to fill in. Create and initialize tensorflow graph placeholders and variables 






# establish the loss function and gradient descent optimizer operations





In [97]:
sess = tf.InteractiveSession()
tf.global_variables_initializer().run()

In [98]:
# generate loop to train algorithm




In [99]:
# store correct_predictions list, and calculate accuracy


In [100]:
#test your predictions, using built in test dataset


0.9094
